version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/ArchipelagoDebugClient/"
    schedule:
      interval: "weekly"
    groups:
      avalonia-core:
        patterns:
          - "Avalonia*"
        exclude-patterns:
          - "Avalonia.Controls.TreeDataGrid"
          - "Avalonia.Xaml.Behaviors"
